[project]
name = "server-fp-insis-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=4.3.0",
    "donttrust>=0.1.5",
    "paho-mqtt>=2.1.0",
    "prisma>=0.15.0",
    "pyjwt>=2.10.1",
]
